apiVersion: v1
kind: Service
metadata:
  name: devops-microservices-{{ .Values.appVersion }} 
  namespace: devops-microservices
spec:
  type: LoadBalancer 
  ports:
  - name: https
    port: 443
    targetPort: 3443
  selector:
    app: devops-microservices-{{ .Values.appVersion }}
