apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-microservices-ingress-{{ .Values.majorVersion }}
  namespace: devops-microservices
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.global-static-ip-name: devops-microservices-ip
spec:
  tls:
  - hosts:
    - "gcp.nestorurquiza.com"
    secretName: devops-microservices-tls
  rules:
  - host: "gcp.nestorurquiza.com"
    http:
      paths:
      - path: /v{{ .Values.majorVersion }}/
        pathType: Prefix
        backend:
          service:
            name: devops-microservices-{{ .Values.majorVersion }}
            port:
              number: 80 

