apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-microservices-ingress
  namespace: devops-microservices
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /v{{ .Values.appVersion }}/
        pathType: Prefix
        backend:
          service:
            name: devops-microservices-{{ .Values.appVersion }}
            port:
              number: 443

