apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: devops-microservices
  annotations:
    "helm.sh/hook": pre-install
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nestor.urquiza@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - http01:
        ingress:
          class: nginx

